### ISSUE TITLE
Monoid Instance

### ISSUE THREAD

**Issue by genos** [haskellari/these#172]
Hello!

First of all, thank you _so_ much for this _very_ useful library, I really appreciate it.

Second, in order to avoid defining dreaded orphan instances or needlessly wrapping things in `newtype`, I'd like to make a small suggestion: a `Monoid` instance. Just like we've got `instance (Semigroup a, Semigroup b) => Semigroup (These a b)`, I'd like to propose a simple `instance (Monoid a, Monoid b) => Monoid (These a b)` à la

```haskell
instance (Monoid a, Monoid b) => Monoid (These a b) where
  mempty = These mempty mempty
```

Cheers!

**Comment by mitchellwrosen** [comment]
I don't think this instance is lawful, unfortunately.

By the monoid laws,

```
This x <> mempty
```

should return

```
This x
```

but with your suggested instance, it would instead return

```
These x mempty
```

**Comment by genos** [comment]
Very good point @mitchellwrosen! Thanks for finding that.

Would updating the Semigroup instance make sense instead? It’d be a much larger (breaking) change.

**Comment by mitchellwrosen** [comment]
I'd vote for neither of the above - don't define an unlawful instance here, nor in your own private code ;)

**Comment by genos** [comment]
Ha! Agreed, in an ideal world. But! My use case is a JSON aggregation demo; combining is the main point, but being able to accumulate errors or OK parses or both would be ideal.

**Comment by mitchellwrosen** [comment]
I see. Could you parse a non-empty collection, then, which only needs a Semigroup instance?

**Comment by genos** [comment]
Perhaps in specific (none of my examples are “parse this empty string?”) but in general I am stuck with the monoid requirements.

That said, my self-deployed plight isn’t the library’s fault! I’ll close this issue out, and thanks again for talking things through with me.
