### ISSUE TITLE
"unalign can be defined for any Functor" - incorrect?

### ISSUE THREAD

**Issue by LightAndLight** [haskellari/these#185]
[The README](https://github.com/haskellari/these/blob/a0baaaf53230dc6661809023ee594f9395017e21/README.md#L41) says [`unalign`](https://hackage.haskell.org/package/semialign-1.3/docs/Data-Semialign.html#t:Unalign) can be defined for any Functor. Am I missing something? That doesn't seem right:

```haskell
unalignDefault :: Functor f => f (These a b) -> (f a, f b)
unalignDefault xs =
  ( fmap (\case; This a -> a; That b -> _ :: a; These a _ -> a) xs
  , fmap (\case; This a -> _ :: b; That b -> b; These _ b -> b) xs
  )
```

There are holes we can't fill.

Interestingly, it would seem that`unalign` *can* be implemented for any [`Filterable`](https://hackage.haskell.org/package/witherable-0.4.2/docs/Witherable.html). I don't know if it's lawful:

```haskell
unalignDefault :: Filterable f => f (These a b) -> (f a, f b)
unalignDefault xs =
  ( mapMaybe (\case; This a -> Just a; That _ -> Nothing; These a _ -> Just a) xs
  , mapMaybe (\case; This _ -> Nothing; That b -> Just b; These _ b -> Just b) xs
  )
```

Given the compatibility note in the `unalign` docs, I'm guessing that the README was written about [this version](https://hackage.haskell.org/package/these-0.8.1/docs/Data-Align.html#v:unalign), before `semialign` was split out of `these`.

I'll submit a PR soon.

**Comment by phadej** [comment]
Given that README haven't been touched in 8 years, and I'm not the one wrote that, it could be a mistake.
