### ISSUE TITLE
Support GHC 9.10

### ISSUE THREAD

**Issue by ulysses4ever** [haskellari/these#195]

**Comment by andreasabel** [comment]
> [__3] rejecting: base-4.20.0.0/installed-8a80 (conflict: these => base>=4.5.1.0 && <4.20)

**Comment by ysangkok** [comment]
semialign-1.3.1 and [these-1.2.1](https://hackage.haskell.org/package/these) were uploaded on May 16th and supports GHC 9.10. So I think this can be closed.
